// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddDateEventTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addDateEvent() {
    driver.get("http://m2gl.deptinfo-st.univ-fcomte.fr/~m2test3/preprod/index.php");
    driver.manage().window().setSize(new Dimension(1382, 784));
    driver.findElement(By.linkText("ici")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("testadmin@test.com");
    driver.findElement(By.name("password")).sendKeys("12345678");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("event")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) > a")).click();
    driver.findElement(By.linkText("Ajouter Date")).click();
    driver.findElement(By.name("DateEvent_j")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateEvent_j"));
      dropdown.findElement(By.xpath("//option[. = '11']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(1) > option:nth-child(11)")).click();
    driver.findElement(By.name("DateEvent_m")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateEvent_m"));
      dropdown.findElement(By.xpath("//option[. = 'Octobre']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(2) > option:nth-child(10)")).click();
    driver.findElement(By.name("DateEvent_hr")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateEvent_hr"));
      dropdown.findElement(By.xpath("//option[. = '16']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(5) > option:nth-child(17)")).click();
    driver.findElement(By.name("btnValiderAjoutDate")).click();
  }
}
