// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddEventTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addEvent() {
    driver.get("http://m2gl.deptinfo-st.univ-fcomte.fr/~m2test3/preprod/index.php");
    driver.manage().window().setSize(new Dimension(550, 692));
    driver.findElement(By.linkText("Ajouter un évènement")).click();
    driver.findElement(By.id("lien_connect")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("cborde414@gmail.com");
    driver.findElement(By.name("password")).sendKeys("Azerty1234!");
    driver.findElement(By.name("btnConnexion")).click();
    driver.findElement(By.name("NameEvent")).click();
    driver.findElement(By.name("NameEvent")).sendKeys("Soirée");
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.name("LieuEvent")).click();
    driver.findElement(By.name("LieuEvent")).sendKeys("Bar");
    driver.findElement(By.name("DateEvent1_j")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateEvent1_j"));
      dropdown.findElement(By.xpath("//option[. = '10']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(3) select:nth-child(1) > option:nth-child(10)")).click();
    driver.findElement(By.name("DateEvent1_m")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateEvent1_m"));
      dropdown.findElement(By.xpath("//option[. = 'Octobre']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(3) select:nth-child(2) > option:nth-child(10)")).click();
    driver.findElement(By.name("DateEvent1_hr")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateEvent1_hr"));
      dropdown.findElement(By.xpath("//option[. = '18']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(3) select:nth-child(5) > option:nth-child(19)")).click();
    driver.findElement(By.name("DateCloture_j")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateCloture_j"));
      dropdown.findElement(By.xpath("//option[. = '9']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(8) select:nth-child(1) > option:nth-child(9)")).click();
    driver.findElement(By.name("DateCloture_m")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateCloture_m"));
      dropdown.findElement(By.xpath("//option[. = 'Octobre']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(8) select:nth-child(2) > option:nth-child(10)")).click();
    driver.findElement(By.name("DateCloture_j")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateCloture_j"));
      dropdown.findElement(By.xpath("//option[. = '11']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(8) select:nth-child(1) > option:nth-child(11)")).click();
    driver.findElement(By.name("DateCloture_m")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateCloture_m"));
      dropdown.findElement(By.xpath("//option[. = 'Novembre']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(8) select:nth-child(2) > option:nth-child(11)")).click();
    driver.findElement(By.name("DateEvent1_j")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateEvent1_j"));
      dropdown.findElement(By.xpath("//option[. = '14']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(3) select:nth-child(1) > option:nth-child(14)")).click();
    driver.findElement(By.name("DateEvent1_m")).click();
    {
      WebElement dropdown = driver.findElement(By.name("DateEvent1_m"));
      dropdown.findElement(By.xpath("//option[. = 'Novembre']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(3) select:nth-child(2) > option:nth-child(11)")).click();
    driver.findElement(By.name("btnValiderEvent")).click();
    driver.findElement(By.cssSelector("button")).click();
  }
}
